SELECT professorId, name, patronymic, year, studyDay, title, floor, classroom
FROM SCHEDULE
    INNER JOIN PROFESSORS ON PROFESSORS.id = SCHEDULE.professorId
    INNER JOIN UNIVERSITY_COURSES ON UNIVERSITY_COURSES.id = SCHEDULE.courseId
    INNER JOIN UNIVERSITY_LECTURES ON UNIVERSITY_LECTURES.id = SCHEDULE.lectureId
    INNER JOIN LECTURE_HALLS ON LECTURE_HALLS.id = SCHEDULE.lectureHallId
    ORDER BY professorId;