CREATE TABLE UNIVERSITY_GROUPS
(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
courseId INT NOT NULL CHECK (courseId <= 5),
FOREIGN KEY (courseId)  REFERENCES UNIVERSITY_COURSES (id),
CONSTRAINT sc_unique_groups5 UNIQUE (courseId)
);

GO