DROP TABLE IF EXISTS GROUPS;
CREATE TABLE GROUPS 
(
group_id SERIAL PRIMARY KEY, 
group_name TEXT NOT NULL
);
DROP TABLE IF EXISTS COURSES;
CREATE TABLE courses
(
course_id SERIAL PRIMARY KEY,
course_name TEXT NOT NULL,
course_description TEXT NOT NULL
);
DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE students
(
student_id SERIAL PRIMARY KEY,
group_id INTEGER,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL
);
DROP TABLE IF EXISTS STUDENTS_COURSES;
CREATE TABLE students_courses
(
student_id INTEGER,
course_id INTEGER,
FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT sc_unique UNIQUE (student_id, course_id)
);