DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS COURSES_GROUPS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS PROFESSORS;
DROP TABLE IF EXISTS lectures;
DROP TABLE IF EXISTS lecture_halls;
DROP TABLE IF EXISTS schedule_Item;