DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS PROFESSORS;
DROP TABLE IF EXISTS lectures;
DROP TABLE IF EXISTS lecturehalls;
DROP TABLE IF EXISTS scheduleItem;